Display severity in human format results
Lightning-Flow-Scanner/lightning-flow-scanner-sfdx pull request #87
Opened 2024-03-14 22:26 UTC by nvuillam

- Severity in flow errors details
- Summary of number of issues by severity
- yarn.lock has been updated after I run "yarn" at the root, and i'm using yarn latest version so I think it's correct

Screenshot of the result :)

![image](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-sfdx/assets/17500430/274d31e6-2d76-4a84-bd13-b45a7e058d62)

2024-03-14 22:27 UTC, nvuillam commented
@RubenHalman FYI :)

2024-03-16 10:38 UTC, RubenHalman commented
@nvuillam Awesome! If you can please leave out the changes to the yarn lock file, we can merge this!

2024-03-16 10:39 UTC, RubenHalman commented on yarn.lock
Please leave the yarn changes out of the PR

2024-03-16 10:42 UTC, RubenHalman requested changes
@nvuillam Awesome! If you can please leave out the changes to the yarn lock file, we can merge this immidiately!

2024-03-16 10:46 UTC, nvuillam commented
@RubenHalman done :)

2024-03-16 11:01 UTC, RubenHalman approved these changes

2024-03-16 11:02 UTC, merged

2024-03-16 12:52 UTC, RubenHalman commented
Thank you for your contribution. This change is now included in version [2.19](https://github.com/Lightning-Flow-Scanner/lightning-flow-scanner-sfdx/releases/tag/2.19)